---
- name: Ansible Create login user 
  hosts: Web1
  remote_user: root
  tasks:
    - name: Add the user 'rockyLab4_user' with a specific uid and a primary group of 'sudo'
      ansible.builtin.user:
        name: rockyLab4_user
        comment: rockyLab_user
        uid: 1077
        group: sudo
        createhome: yes        
        home: /home/rockyLab4_user

