---
- name: Ansible Create login user 
  hosts: Web1
  remote_user: root
  tasks:
    - name: Add the user 'ubuntuLab4_user' with a specific uid and a primary group of 'sudo'
      ansible.builtin.user:
        name: ubuntuLab4_user
        comment: ubuntuLab_user
        uid: 1077
        group: sudo
        createhome: yes        
        home: /home/ubuntuLab4_user

